### ISSUE TITLE
Post Deliverable Checklist - Sprint 2

### ISSUE THREAD

**Issue by shakeel-nazir** [shakeel-nazir/simple-chat-app#13]
# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left
- [ ] Interactive Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left
- [ ] Complete Project
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

# Issues
Completed: #11

# Positives :+1:

+ I found that having all the assets already created it in XD really helped my workflow. (Shak)
+ It really helped me that the task that I was assigned was the same one that I designed initially. (Shak)
+ I second what Shakeel says, as well I'm happy there were more than one option to complete the wireframes. (Ash)
+ I like using codepen as a search tool to learn how to make the popup (Mary)

# Improvements :star:

+ I feel like if I managed my time a little bit better I would have gotten more work done. (Shak)
+ I wish I used my code editor instead of Codepen. I'm worried transferring my code over to the simple-chat won't be as smooth. (Ash)
+ it was hard to work with codepen, but i like the immediate response (Mary)

# Request for Feedback :ear:

+ @ericadamski do you feel like all of our individual designs work well with each other?
+ ...
+ ...
